services:
  site2:
    image: nginx:alpine
    container_name: site2-frontend
    ports:
      - "8081:80"
    volumes:
      - /srv/apps/Brechtwahl/<look-what-i-can-do>:/usr/share/nginx/html:ro
      - /srv/apps/Brechtwahl/<look-what-i-can-do>/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped